// <auto-generated />
using System;
using DoAn.Models.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoAn.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DoAn.Models.Domain.LoaiSp", b =>
                {
                    b.Property<int>("MaLoaiSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("TenLoaiSp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoaiSp");

                    b.ToTable("LoaiSp");
                });

            modelBuilder.Entity("DoAn.Models.Domain.SanPham", b =>
                {
                    b.Property<int>("MaSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LoaiSpMaLoaiSp")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiSp")
                        .HasColumnType("int");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSp");

                    b.HasIndex("LoaiSpMaLoaiSp");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("DoAn.Models.Domain.SanPham", b =>
                {
                    b.HasOne("DoAn.Models.Domain.LoaiSp", "LoaiSp")
                        .WithMany("SanPhams")
                        .HasForeignKey("LoaiSpMaLoaiSp");

                    b.Navigation("LoaiSp");
                });

            modelBuilder.Entity("DoAn.Models.Domain.LoaiSp", b =>
                {
                    b.Navigation("SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
